import { Employee } from "../app/models/employee.model";

export const employeesData: Employee[] = [
    {
        id: '1',
        username: 'john_doe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        birthDate: new Date('1990-01-01'),
        basicSalary: 500000000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Engineer'
    },
    {
        id: '2',
        username: 'jane_smith',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        birthDate: new Date('1991-02-15'),
        basicSalary: 600000000,
        status: 'Active',
        group: 'Marketing',
        description: 'Marketing Manager'
    },
    {
        id: '3',
        username: 'michael_johnson',
        firstName: 'Michael',
        lastName: 'Johnson',
        email: 'michael.johnson@example.com',
        birthDate: new Date('1985-07-20'),
        basicSalary: 700000000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Representative'
    },
    {
        id: '4',
        username: 'emily_brown',
        firstName: 'Emily',
        lastName: 'Brown',
        email: 'emily.brown@example.com',
        birthDate: new Date('1988-04-05'),
        basicSalary: 550000000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '5',
        username: 'david_williams',
        firstName: 'David',
        lastName: 'Williams',
        email: 'david.williams@example.com',
        birthDate: new Date('1993-09-10'),
        basicSalary: 480000000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Developer'
    },
    {
        id: '6',
        username: 'sarah_jones',
        firstName: 'Sarah',
        lastName: 'Jones',
        email: 'sarah.jones@example.com',
        birthDate: new Date('1992-11-30'),
        basicSalary: 520000000,
        status: 'Active',
        group: 'Marketing',
        description: 'Marketing Specialist'
    },
    {
        id: '7',
        username: 'robert_white',
        firstName: 'Robert',
        lastName: 'White',
        email: 'robert.white@example.com',
        birthDate: new Date('1987-03-25'),
        basicSalary: 620000000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Manager'
    },
    {
        id: '8',
        username: 'lisa_miller',
        firstName: 'Lisa',
        lastName: 'Miller',
        email: 'lisa.miller@example.com',
        birthDate: new Date('1986-06-12'),
        basicSalary: 580000000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },
    {
        id: '9',
        username: 'peter_davis',
        firstName: 'Peter',
        lastName: 'Davis',
        email: 'peter.davis@example.com',
        birthDate: new Date('1989-08-18'),
        basicSalary: 530000000,
        status: 'Active',
        group: 'Engineering',
        description: 'Front-end Developer'
    },
    {
        id: '10',
        username: 'jennifer_clark',
        firstName: 'Jennifer',
        lastName: 'Clark',
        email: 'jennifer.clark@example.com',
        birthDate: new Date('1994-12-07'),
        basicSalary: 570000000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Writer'
    },
    {
        id: '11',
        username: 'william_thomas',
        firstName: 'William',
        lastName: 'Thomas',
        email: 'william.thomas@example.com',
        birthDate: new Date('1984-02-28'),
        basicSalary: 640000000,
        status: 'Active',
        group: 'Sales',
        description: 'Business Development Manager'
    },
    {
        id: '12',
        username: 'amanda_scott',
        firstName: 'Amanda',
        lastName: 'Scott',
        email: 'amanda.scott@example.com',
        birthDate: new Date('1990-05-14'),
        basicSalary: 590000000,
        status: 'Active',
        group: 'Operations',
        description: 'HR Manager'
    },
    {
        id: '13',
        username: 'matthew_hall',
        firstName: 'Matthew',
        lastName: 'Hall',
        email: 'matthew.hall@example.com',
        birthDate: new Date('1991-07-19'),
        basicSalary: 510000000,
        status: 'Active',
        group: 'Engineering',
        description: 'Backend Developer'
    },
    {
        id: '14',
        username: 'laura_martin',
        firstName: 'Laura',
        lastName: 'Martin',
        email: 'laura.martin@example.com',
        birthDate: new Date('1988-09-22'),
        basicSalary: 550000000,
        status: 'Active',
        group: 'Marketing',
        description: 'Social Media Specialist'
    },
    {
        id: '15',
        username: 'kevin_adams',
        firstName: 'Kevin',
        lastName: 'Adams',
        email: 'kevin.adams@example.com',
        birthDate: new Date('1986-11-11'),
        basicSalary: 560000000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Executive'
    },
    {
        id: '16',
        username: 'melissa_wilson',
        firstName: 'Melissa',
        lastName: 'Wilson',
        email: 'melissa.wilson@example.com',
        birthDate: new Date('1993-01-25'),
        basicSalary: 600000000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Analyst'
    },
    {
        id: '17',
        username: 'steven_robinson',
        firstName: 'Steven',
        lastName: 'Robinson',
        email: 'steven.robinson@example.com',
        birthDate: new Date('1985-03-17'),
        basicSalary: 490000000,
        status: 'Active',
        group: 'Engineering',
        description: 'DevOps Engineer'
    },
    {
        id: '18',
        username: 'christina_thompson',
        firstName: 'Christina',
        lastName: 'Thompson',
        email: 'christina.thompson@example.com',
        birthDate: new Date('1992-06-30'),
        basicSalary: 580000000,
        status: 'Active',
        group: 'Marketing',
        description: 'Graphic Designer'
    },
    {
        id: '19',
        username: 'george_carter',
        firstName: 'George',
        lastName: 'Carter',
        email: 'george.carter@example.com',
        birthDate: new Date('1989-08-05'),
        basicSalary: 510000000,
        status: 'Active',
        group: 'Sales',
        description: 'Customer Service Manager'
    },
    {
        id: '20',
        username: 'stephanie_evans',
        firstName: 'Stephanie',
        lastName: 'Evans',
        email: 'stephanie.evans@example.com',
        birthDate: new Date('1987-10-12'),
        basicSalary: 530000000,
        status: 'Active',
        group: 'Operations',
        description: 'Supply Chain Coordinator'
    },
    {
        id: '21',
        username: 'patrick_morris',
        firstName: 'Patrick',
        lastName: 'Morris',
        email: 'patrick.morris@example.com',
        birthDate: new Date('1990-12-15'),
        basicSalary: 540000000,
        status: 'Active',
        group: 'Engineering',
        description: 'Systems Analyst'
    },
    {
        id: '22',
        username: 'rachel_ward',
        firstName: 'Rachel',
        lastName: 'Ward',
        email: 'rachel.ward@example.com',
        birthDate: new Date('1986-02-28'),
        basicSalary: 570000000,
        status: 'Active',
        group: 'Marketing',
        description: 'SEO Specialist'
    },
    {
        id: '23',
        username: 'eric_roberts',
        firstName: 'Eric',
        lastName: 'Roberts',
        email: 'eric.roberts@example.com',
        birthDate: new Date('1993-04-10'),
        basicSalary: 520000000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Analyst'
    },
    {
        id: '24',
        username: 'samantha_wood',
        firstName: 'Samantha',
        lastName: 'Wood',
        email: 'samantha.wood@example.com',
        birthDate: new Date('1988-06-05'),
        basicSalary: 590000000,
        status: 'Active',
        group: 'Operations',
        description: 'Financial Analyst'
   
    }];